### ISSUE TITLE
HdelWithTxn:  panic: interface conversion: interface {} is nil, not uint64

### ISSUE THREAD

**Issue by rohitjoshi** [yongman/tidis#21]
```
127.0.0.1:5379> hdel hash2 token3
Error: Connection reset by peer
```

```
panic: interface conversion: interface {} is nil, not uint64

goroutine 259 [running]:
github.com/yongman/tidis/tidis.(*Tidis).HdelWithTxn(0xc4200a2a80, 0x1880160, 0xc420466b00, 0xc4200c0b60, 0x5, 0x5, 0xc4208bdb60, 0x1, 0x1, 0x1689134, ...)
	/Users/user/projects/go/src/github.com/yongman/tidis/tidis/t_hash.go:205 +0x2e8
github.com/yongman/tidis/tidis.(*Tidis).Hdel.func1(0x1880160, 0xc420466b00, 0xc420466b00, 0x0, 0x0, 0x1819d20)
	/Users/user/projects/go/src/github.com/yongman/tidis/tidis/t_hash.go:124 +0x81
github.com/yongman/tidis/store/tikv.(*Tikv).BatchInTxn(0xc4201a03a0, 0xc420401580, 0x18f3eb0, 0xc420991cb0, 0xc4207e4000, 0xc420991ca0)
	/Users/user/projects/go/src/github.com/yongman/tidis/store/tikv/tikv.go:536 +0xcf
github.com/yongman/tidis/tidis.(*Tidis).Hdel(0xc4200a2a80, 0xc4200c0b60, 0x5, 0x5, 0xc4208bdb60, 0x1, 0x1, 0x10, 0x1, 0xc420344768)
	/Users/user/projects/go/src/github.com/yongman/tidis/tidis/t_hash.go:128 +0xcc
github.com/yongman/tidis/server.hdelCommand(0xc4201a2c60, 0xc42028fb00, 0xc4200c0b6c)
	/Users/user/projects/go/src/github.com/yongman/tidis/server/command_hash.go:119 +0x193
github.com/yongman/tidis/server.(*Client).execute(0xc4201a2c60, 0x4, 0x18a712f)
	/Users/user/projects/go/src/github.com/yongman/tidis/server/client.go:350 +0x1fd
github.com/yongman/tidis/server.(*Client).handleRequest(0xc4201a2c60, 0xc4208bdb30, 0x3, 0x3, 0x0, 0x0)
	/Users/user/projects/go/src/github.com/yongman/tidis/server/client.go:335 +0x5a0
github.com/yongman/tidis/server.(*Client).connHandler(0xc4201a2c60)
	/Users/user/projects/go/src/github.com/yongman/tidis/server/client.go:211 +0x190
created by github.com/yongman/tidis/server.ClientHandler
	/Users/user/projects/go/src/github.com/yongman/tidis/server/client.go:86 +0x254
```

**Comment by yongman** [comment]
Fixed.

Thanks for your test. This case will be added to unit test cases.

Any PRs will be welcomed. :-)
