### ISSUE TITLE
panic: interface conversion: interface {} is nil, not int

### ISSUE THREAD

**Issue by rohitjoshi** [yongman/tidis#24]
```
WARN[0810] ttl checker hashkey failed, [tikv:9001]PD server timeout[try again later]
WARN[0810] BatchInTxn execute failed
panic: interface conversion: interface {} is nil, not int

goroutine 135 [running]:
github.com/yongman/tidis/tidis.(*ttlChecker).Run(0xc42015c4c0)
	/Users/xxxx/projects/go/src/github.com/yongman/tidis/tidis/ttl.go:169 +0x1350
created by github.com/yongman/tidis/server.(*App).Run
	/Users/xxxx/projects/go/src/github.com/yongman/tidis/server/app.go:83 +0x197
```

**Comment by yongman** [comment]
Confirmed.

Return value should not be asserted in debug log.
